import {
  amber,
  blue,
  blueGrey,
  brown,
  cyan,
  deepOrange,
  deepPurple,
  green,
  indigo,
  lightBlue,
  lightGreen,
  lime,
  orange,
  pink,
  purple,
  red,
  teal,
  yellow,
} from '@mui/material/colors';

export const additionTheme = {
  light: {
    // palette values for light mode
    red: {
      light: red[300],
      main: red[500],
      dark: red[700],
      contrastText: '#000',
    },
    pink: {
      light: pink[300],
      main: pink[500],
      dark: pink[700],
      contrastText: '#000',
    },
    purple: {
      light: purple[300],
      main: purple[500],
      dark: purple[700],
      contrastText: '#000',
    },
    deepPurple: {
      light: deepPurple[300],
      main: deepPurple[500],
      dark: deepPurple[700],
      contrastText: '#000',
    },
    indigo: {
      light: indigo[300],
      main: indigo[500],
      dark: indigo[700],
      contrastText: '#000',
    },
    blue: {
      light: blue[300],
      main: blue[500],
      dark: blue[700],
      contrastText: '#000',
    },
    lightBlue: {
      light: lightBlue[300],
      main: lightBlue[500],
      dark: lightBlue[700],
      contrastText: '#000',
    },
    cyan: {
      light: cyan[300],
      main: cyan[500],
      dark: cyan[700],
      contrastText: '#000',
    },
    teal: {
      light: teal[300],
      main: teal[500],
      dark: teal[700],
      contrastText: '#000',
    },
    green: {
      light: green[300],
      main: green[500],
      dark: green[700],
      contrastText: '#000',
    },
    lightGreen: {
      light: lightGreen[300],
      main: lightGreen[500],
      dark: lightGreen[700],
      contrastText: '#000',
    },
    lime: {
      light: lime[300],
      main: lime[500],
      dark: lime[700],
      contrastText: '#000',
    },
    yellow: {
      light: yellow[300],
      main: yellow[500],
      dark: yellow[700],
      contrastText: '#000',
    },
    amber: {
      light: amber[300],
      main: amber[500],
      dark: amber[700],
      contrastText: '#000',
    },
    orange: {
      light: orange[300],
      main: orange[500],
      dark: orange[700],
      contrastText: '#000',
    },
    deepOrange: {
      light: deepOrange[300],
      main: deepOrange[500],
      dark: deepOrange[700],
      contrastText: '#000',
    },
    brown: {
      light: brown[300],
      main: brown[500],
      dark: brown[700],
      contrastText: '#000',
    },
    blueGrey: {
      light: blueGrey[300],
      main: blueGrey[500],
      dark: blueGrey[700],
      contrastText: '#000',
    },
  },
  dark: {
    // palette values for dark mode
    red: {
      light: red[50],
      main: red[100],
      dark: red[300],
      contrastText: '#fff',
    },
    pink: {
      light: pink[50],
      main: pink[100],
      dark: pink[300],
      contrastText: '#fff',
    },
    purple: {
      light: purple[50],
      main: purple[100],
      dark: purple[300],
      contrastText: '#fff',
    },
    deepPurple: {
      light: deepPurple[50],
      main: deepPurple[100],
      dark: deepPurple[300],
      contrastText: '#fff',
    },
    indigo: {
      light: indigo[50],
      main: indigo[100],
      dark: indigo[300],
      contrastText: '#fff',
    },
    blue: {
      light: blue[50],
      main: blue[100],
      dark: blue[300],
      contrastText: '#fff',
    },
    lightBlue: {
      light: lightBlue[50],
      main: lightBlue[100],
      dark: lightBlue[300],
      contrastText: '#fff',
    },
    cyan: {
      light: cyan[50],
      main: cyan[100],
      dark: cyan[300],
      contrastText: '#fff',
    },
    teal: {
      light: teal[50],
      main: teal[100],
      dark: teal[300],
      contrastText: '#fff',
    },
    green: {
      light: green[50],
      main: green[100],
      dark: green[300],
      contrastText: '#fff',
    },
    lightGreen: {
      light: lightGreen[50],
      main: lightGreen[100],
      dark: lightGreen[300],
      contrastText: '#000',
    },
    lime: {
      light: lime[50],
      main: lime[100],
      dark: lime[300],
      contrastText: '#000',
    },
    yellow: {
      light: yellow[50],
      main: yellow[100],
      dark: yellow[300],
      contrastText: '#000',
    },
    amber: {
      light: amber[50],
      main: amber[100],
      dark: amber[300],
      contrastText: '#fff',
    },
    orange: {
      light: orange[50],
      main: orange[100],
      dark: orange[300],
      contrastText: '#fff',
    },
    deepOrange: {
      light: deepOrange[50],
      main: deepOrange[100],
      dark: deepOrange[300],
      contrastText: '#fff',
    },
    brown: {
      light: brown[50],
      main: brown[100],
      dark: brown[300],
      contrastText: '#fff',
    },
    blueGrey: {
      light: blueGrey[50],
      main: blueGrey[200],
      dark: blueGrey[300],
      contrastText: '#fff',
    },
  },
};
